import Head from "next/head";
import style from "../styles/layout.module.css";
import Navbar from "./navbar";
import ShoppingCart from "./shoppingCart";
export default function Layout({children,title}){
    return (
      <div>
        <Head>
          <title>Github Merche {title?`| ${title}`:''}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar/>
        <div className={style.container}>
            {children}
        </div>
        <ShoppingCart/>
      </div>
    );
}